[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Filesystem yang dipakai untuk serve HTML/CSS/JS dari folder data/
board_build.filesystem = littlefs

; Sesuaikan port kalau perlu, contoh:
upload_port = COM3
monitor_port = COM3

monitor_speed = 115200

lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    madhephaestus/ESP32Servo @ ^1.1.1